language: go
sudo: required

go:
    #- "1.9"
    - "1.10"
    #- tip

go_import_path: gopkg.in/goracle.v2

addons:
  apt:
    packages:
      - libaio1

env:
    # alias travis='docker run --rm -v $PWD:/repo -v ~/.travis:/travis andredumas/travis-ci-cli'
    # travis encrypt -r tgulacsi/ora  'AWS_ACCESS_KEY_ID=...' 'AWS_SECRET_ACCESS_KEY=...+hMtiMhFbmUhu2zB+UyjUdGveIMvWBRIV' 'GO_ORA_DRV_TEST_DB=host:port/sid' GO_ORA_DRV_TEST_USERNAME=... GO_ORA_DRV_TEST_PASSWORD=...
  global:
    - secure: "OksEWQRpzRuwmO3LkXfHk7DQWNUZgeI8iM2DJlCY7g/89gVCKMy4dUyuPAdnU7dYKXIb51KIpwgwM+iOHzRPKRt92CwM3A/lfqOLabZs0JuwOp1LTN9A3fLEU1nqfqyXeSA6+TMy1n3RWm80KCOrH/vwouSPJL3KFITci8jUE6g="
    - GORACLE_DRV_TEST_USERNAME=test
    - GORACLE_DRV_TEST_PASSWORD=test
    - GORACLE_DRV_TEST_DB=oracle.gthomas.eu:49161/xe

before_install:
    - wget https://github.com/barnybug/s3/releases/download/1.1.7/s3-linux-amd64 && mv s3-linux-amd64 s3 && chmod +x s3
    - ./s3 get s3://tgulacsi-oracle-instantclient/
    - sudo apt-get install libaio1
    - sudo dpkg -i oracle-instantclient12.1-basiclite_12.1.0.2.0-2_amd64.deb
    - sudo dpkg -i oracle-instantclient12.1-devel_12.1.0.2.0-2_amd64.deb
    - echo /usr/lib/oracle/12.1/client64/lib/ | sudo tee /etc/ld.so.conf.d/oracle.conf && sudo ldconfig
    - export CGO_CFLAGS=-I/usr/include/oracle/12.1/client64
    - export CGO_LDFLAGS=-L/usr/lib/oracle/12.1/client64/lib

install:
    - go get -t .

script:
    - go test -coverprofile=coverage.txt -covermode=atomic .

after_success:
    - bash <(curl -s https://codecov.io/bash)
